### PR TITLE
Fix Bootstraps to return the Promise when calling to init method

### LINKED ISSUE #55: window.__cmp not ready after bootstrap initialization
**SUMMARY**
When the boros-cmp is imported and the init method is called it's expected to be able to use the window.__cmp function, but there's a race condition as the initialization runs in a Promise.

**STEPS TO REPRODUCE**
* Import the project
* Call the init method
* Call any window.__cmp command

**EXPECTED RESULT**
* The command is consumed with the window.__cmp function

**ACTUAL RESULT**
* There's a random error (race condition) indicating that window.__cmp is not a function

### PR DESCRIPTION
**Pull request by rafamarquezv**
### Fix Bootstraps to return the Promise when calling to init method

* Both bootstraps (global and local) returns Promise when calling to init method.
* Test added for Both bootstraps (global and local)
* Fix Lint problems
* Update Readme file
* Fix coverage task to find tests
* Version upgraded

Fixes #55

### CODE REVIEW

File: src/cmp/infrastructure/bootstrap/LocalStorageBootstrap.js [hunk 1]
```diff
@@ -6,7 +6,7 @@ import registerCmpLocator from '../controller/registerCmpLocator'
 
 export default class LocalStorageBootstrap {
   static init({window, config}) {
-    Promise.resolve()
+    return Promise.resolve()
```
Comment (victuxbb) [inline src/cmp/infrastructure/bootstrap/LocalStorageBootstrap.js]: Nice Return!

Comment (rafamarquezv) [reply src/cmp/infrastructure/bootstrap/LocalStorageBootstrap.js]: ^_^
